# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: SampleDemo
trigger:
- main
pool:
 name: default
steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: Npm@1
  inputs:
    command: 'install'
